services:
  memento-prod:
    container_name: memento-prod
    build:
      context: .
      dockerfile: production.Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
