services:
  memento:
    container_name: memento-dev
    image: oven/bun:alpine
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "${PORT}:${PORT}"
      - "${HMR_PORT}:${HMR_PORT}"
    volumes:
      - ./app:/app
    working_dir: /app
    command: bun run dev
