services:
  memento:
    container_name: memento-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "${PORT}:${PORT}"
      - "${HMR_PORT}:${HMR_PORT}"
    working_dir: /app
    command: bun run preview
