services:
  memento:
    container_name: memento-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
