services:
  memento-dev:
    container_name: memento-dev
    build:
      context: .
      dockerfile: pnpm.Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "${HMR_PORT}:${HMR_PORT}"
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - memento-data

  memento-dev-redis:
    container_name: memento-dev-redis
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - memento-data

networks:
  memento-data:
    driver: bridge
