/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Memento Dev",
  "tagline": "Souviens-toi que tu développeras.",
  "favicon": "img/favicon.webp",
  "url": "https://memento-dev.fr",
  "baseUrl": "/",
  "organizationName": "preparation-tp",
  "projectName": "memento-dev",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "scripts": [
    {
      "src": "https://cloud.umami.is/script.js",
      "async": true,
      "defer": true,
      "data-website-id": "ba70261e-d145-4dd1-b0e8-27cbf4927b74"
    }
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "i18n": {
    "defaultLocale": "fr",
    "locales": [
      "fr"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": false,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "/img/favicon.webp"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "#7c3aed"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "#242526"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "/img/favicon.webp"
          },
          {
            "tagName": "link",
            "rel": "mask-icon",
            "href": "/img/favicon.webp",
            "color": "#7c3aed"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "/img/favicon.webp"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#7c3aed"
          }
        ]
      }
    ],
    null,
    [
      "/Users/jack/Projets/Perso/memento-dev/node_modules/.pnpm/docusaurus-lunr-search@3.4.0_@docusaurus+core@3.6.1_@mdx-js+react@3.0.1_@types+react@18.3.3_r_qkss22oxrb6lqvbuqsivdrac7q/node_modules/docusaurus-lunr-search/src/index.js",
      {
        "languages": [
          "fr"
        ]
      }
    ],
    [
      "@docusaurus/plugin-sitemap",
      {
        "lastmod": "date",
        "changefreq": "weekly",
        "priority": 0.5,
        "ignorePatterns": [
          "/tags/**"
        ],
        "filename": "sitemap.xml",
        "id": "sitemap"
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/preparation-tp/memento-dev/tree/main/",
          "admonitions": {
            "keywords": [
              "quote",
              "example"
            ],
            "extendDefaults": true
          },
          "routeBasePath": "/",
          "tagsBasePath": "tags"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "dark"
      },
      "options": {}
    },
    "navbar": {
      "style": "dark",
      "title": "Memento Dev",
      "logo": {
        "alt": "Logo Memento Dev",
        "src": "img/logo.webp"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "position": "left",
          "label": "Ressources",
          "items": [
            {
              "label": "Préambule",
              "to": "/intro"
            },
            {
              "label": "Front-end",
              "to": "/category/-frontend"
            },
            {
              "label": "Bases de données",
              "to": "/category/-bases-de-données"
            }
          ]
        },
        {
          "position": "left",
          "label": "Titres professionnels",
          "items": [
            {
              "label": "CDA",
              "to": "/titres-professionnels/CDA/intro"
            },
            {
              "label": "DWWM",
              "to": "/titres-professionnels/DWWM/intro"
            },
            {
              "label": "Se préparer",
              "to": "/titres-professionnels/se-preparer"
            },
            {
              "label": "Retours d'expériences",
              "to": "/titres-professionnels/retours"
            },
            {
              "label": "Archives",
              "to": "/category/%EF%B8%8F-archives"
            }
          ]
        },
        {
          "href": "https://github.com/preparation-tp/memento-dev",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Ressources",
          "items": [
            {
              "label": "Préambule",
              "to": "/intro"
            },
            {
              "label": "Front-end",
              "to": "/category/-frontend"
            },
            {
              "label": "Bases de données",
              "to": "/category/-bases-de-données"
            }
          ]
        },
        {
          "title": "Titres professionnels",
          "items": [
            {
              "label": "CDA",
              "to": "/titres-professionnels/CDA/intro"
            },
            {
              "label": "DWWM",
              "to": "/titres-professionnels/DWWM/intro"
            },
            {
              "label": "Se préparer",
              "to": "/titres-professionnels/se-preparer"
            },
            {
              "label": "Retours d'expériences",
              "to": "/titres-professionnels/retours"
            },
            {
              "label": "Archives",
              "to": "/category/%EF%B8%8F-archives"
            }
          ]
        },
        {
          "title": "Memento Dev",
          "items": [
            {
              "label": "Mentions légales",
              "to": "/mentions-legales"
            },
            {
              "label": "Contribuer",
              "to": "/contribuer"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/preparation-tp/memento-dev"
            }
          ]
        }
      ],
      "copyright": "<span className=\"text-white/70\">\n        Créé avec ❤️ par\n        <a\n          className=\"transition-colors hover:text-white hover:no-underline\"\n          href=\"https://gauthierdaniels.fr\"\n          target=\"_blank\"\n        >\n          Gauthier Daniels\n        </a>\n      </span>"
    },
    "prism": {
      "theme": {
        "plain": {
          "backgroundColor": "hsl(230, 1%, 98%)",
          "color": "hsl(230, 8%, 24%)"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "cdata"
            ],
            "style": {
              "color": "hsl(230, 4%, 64%)"
            }
          },
          {
            "types": [
              "doctype",
              "punctuation",
              "entity"
            ],
            "style": {
              "color": "hsl(230, 8%, 24%)"
            }
          },
          {
            "types": [
              "attr-name",
              "class-name",
              "boolean",
              "constant",
              "number",
              "atrule"
            ],
            "style": {
              "color": "hsl(35, 99%, 36%)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "hsl(301, 63%, 40%)"
            }
          },
          {
            "types": [
              "property",
              "tag",
              "symbol",
              "deleted",
              "important"
            ],
            "style": {
              "color": "hsl(5, 74%, 59%)"
            }
          },
          {
            "types": [
              "selector",
              "string",
              "char",
              "builtin",
              "inserted",
              "regex",
              "attr-value",
              "punctuation"
            ],
            "style": {
              "color": "hsl(119, 34%, 47%)"
            }
          },
          {
            "types": [
              "variable",
              "operator",
              "function"
            ],
            "style": {
              "color": "hsl(221, 87%, 60%)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "hsl(198, 99%, 37%)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "color": "hsl(230, 8%, 24%)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "backgroundColor": "hsl(220, 13%, 18%)",
          "color": "hsl(220, 14%, 71%)",
          "textShadow": "0 1px rgba(0, 0, 0, 0.3)"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "cdata"
            ],
            "style": {
              "color": "hsl(220, 10%, 40%)"
            }
          },
          {
            "types": [
              "doctype",
              "punctuation",
              "entity"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          },
          {
            "types": [
              "attr-name",
              "class-name",
              "maybe-class-name",
              "boolean",
              "constant",
              "number",
              "atrule"
            ],
            "style": {
              "color": "hsl(29, 54%, 61%)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "hsl(286, 60%, 67%)"
            }
          },
          {
            "types": [
              "property",
              "tag",
              "symbol",
              "deleted",
              "important"
            ],
            "style": {
              "color": "hsl(355, 65%, 65%)"
            }
          },
          {
            "types": [
              "selector",
              "string",
              "char",
              "builtin",
              "inserted",
              "regex",
              "attr-value"
            ],
            "style": {
              "color": "hsl(95, 38%, 62%)"
            }
          },
          {
            "types": [
              "variable",
              "operator",
              "function"
            ],
            "style": {
              "color": "hsl(207, 82%, 66%)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "hsl(187, 47%, 55%)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "php",
        "nginx",
        "bash"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
